#!/bin/sh
# chkconfig: 2345 20 80
# description: Start the weather station application for the embedded system

start() {
    /root/TFG &
}

stop() {
    kill -SIGINT /root/TFG
    wait-delay 2
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    *)
       echo "Usage: $0 {start|stop|restart}"
esac

exit 0 
